name: Reusable deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
      description: The name of the deployable artifact files
      required: false
      default: dist
      type: string
    outputs:
      result: The result of the deployment operation
      value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secrets:
    #   required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.step-result.outputs.step-result }}
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploting & Uploading..."
      - name: Set result output
        id: step-result
        run: echo "::set-output name=step-result::'success'"
      
